### ISSUE TITLE
StreamConcat does not emit an end event

### ISSUE THREAD

**Issue by raine** [sedenardi/node-stream-concat#9]
Is there a reason for the `end: false` option here?

https://github.com/sedenardi/node-stream-concat/blob/master/index.js#L29

It appears that is the reason why `end` event is not emitted when streams concatenated by this library end.

**Comment by sedenardi** [comment]
Per https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options, `end: false` prevents the writer stream (`self`) from ending when the reader ends. Omitting this would prevent us from keeping our StreamConcat open to pipe another stream to it.

**Comment by piranna** [comment]
Maybe should it be emitted explicitly when there's no more streams to consume?

**Comment by sedenardi** [comment]
That's what `self.end()` does at [L27](https://github.com/sedenardi/node-stream-concat/blob/master/index.js#L27), no? Please correct me if I'm wrong, because I honestly haven't seriously dug into this in a while, but my understanding is since I'm calling `.end()`, we should be listening for the [`finish`](https://nodejs.org/api/stream.html#stream_events_finish_and_end) event on the StreamConcat.

**Comment by piranna** [comment]
Calling to `.end()` will make it emit the `finish` event, the `end` event will be emited after that when all data has been consumed. Maybe is this the problem?

Anyway, by using a `Transform` stream you can pipe data directly to it, that I'm not sure if it's desirable... It would make sense to build it as a Transform if instead of acepting an Array of streams in the constructor, it would accept to be piped from a stream of streams, if not maybe it would be better to implement it as a plain `Readable` stream.

**Comment by sedenardi** [comment]
If I recall correctly, I didn't implement it as a `Readable` stream because that would involve consuming the concatenated streams and feeding the contents to a new stream, defeating the flowing nature of streams in the first place (having to implement buffering, dealing with backpressure, etc.).

Taking a step back, what are you doing that you need the `end` event and can't use the `finish` event?

**Comment by sedenardi** [comment]
Closing this for now. Feel free to let me know if it's still an issue.
